const db ={
  the: {chunks: ['th','e'], phonemes: ['DH', 'AH']},
  of: { chunks: ['o', 'f'], phonemes: ['AH', 'V'] },
  and: { chunks: ['a', 'n', 'd'], phonemes: ['AH', 'N', 'D'] },
  to: { chunks: ['t', 'o'], phonemes: ['T', 'UW'] },
  a: { chunks: ['a'], phonemes: ['AH'] },
  in: { chunks: ['i', 'n'], phonemes: ['IH', 'N'] },
  for: { chunks: ['f', 'o', 'r'], phonemes: ['F', 'AO', 'R'] },
  is: { chunks: ['i', 's'], phonemes: ['IH', 'Z'] },
  on: { chunks: ['o', 'n'], phonemes: ['AA', 'N'] },
  that: { chunks: ['th', 'a', 't'], phonemes: ['DH', 'AE', 'T'] },
  by: { chunks: ['b', 'y'], phonemes: ['B', 'AY'] },
  this: { chunks: ['th', 'i', 's'], phonemes: ['DH', 'IH', 'S'] },
  with: { chunks: ['w', 'i', 'th'], phonemes: ['W', 'IH', 'DH'] },
  i: { chunks: ['i'], phonemes: ['AY'] },
  you: { chunks: ['y', 'ou'], phonemes: ['Y', 'UW'] },
  it: { chunks: ['i', 't'], phonemes: ['IH', 'T'] },
  not: { chunks: ['n', 'o', 't'], phonemes: ['N', 'AA', 'T'] },
  or: { chunks: ['o', 'r'], phonemes: ['AO', 'R'] },
  be: { chunks: ['b', 'e'], phonemes: ['B', 'IY'] },
  are: { chunks: ['a', 're'], phonemes: ['AA', 'R'] },
  from: { chunks: ['f', 'r', 'o', 'm'], phonemes: ['F', 'R', 'AH', 'M'] },
  at: { chunks: ['a', 't'], phonemes: ['AE', 'T'] },
  as: { chunks: ['a', 's'], phonemes: ['AE', 'Z'] },
  your: { chunks: ['y', 'ou', 'r'], phonemes: ['Y', 'AO', 'R'] },
  all: { chunks: ['a', 'll'], phonemes: ['AO', 'L'] },
  have: { chunks: ['h', 'a', 've'], phonemes: ['HH', 'AE', 'V'] },
  new: { chunks: ['n', 'ew'], phonemes: ['N', 'UW'] },
  more: { chunks: ['m', 'o', 're'], phonemes: ['M', 'AO', 'R'] },
  an: { chunks: ['a', 'n'], phonemes: ['AE', 'N'] },
  was: { chunks: ['w', 'a', 's'], phonemes: ['W', 'AA', 'Z'] },
  we: { chunks: ['w', 'e'], phonemes: ['W', 'IY'] },
  
}
 
export default db;